version: '3.8'

services:
  user_active_games_bff_app:
    container_name: user_game_statistics_bff_app
    build: .
    restart: unless-stopped
    command: npm run start
    ports:
      - "2902:2902"
    links:
      - user_game_statistics_app
  user_game_statistics_app:
    container_name: user_game_statistics_app
    image: ghcr.io/sudokuru/usergamestatistics:latest
    restart: unless-stopped
    command: npm run start
    ports:
      - "3002:3002"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"